# =============================================================================
# Vagrantfile.erb
# ERB template rendered by Deploy-Lab.ps1 -> New-Vagrantfile.
# DO NOT edit this file directly — edit config.yaml and re-run Deploy-Lab.ps1.
# =============================================================================

# -- Generated by Deploy-Lab.ps1 on 2026-02-26 17:23 --
# Config: /home/bill/source/SQLVagrantLab-1/config.yaml

Vagrant.configure("2") do |config|

  # ── Communicator: WinRM for provisioning ─────────────────────────────────────
  # WinRM is Vagrant's native Windows provisioning path. The Packer box keeps
  # WinRM running at all times (configured by configure-winrm-runtime.ps1 via
  # SetupComplete.cmd on first boot after Sysprep) and OpenSSH for manual SSH.
  config.vm.guest        = :windows
  config.vm.communicator = "winrm"
  config.winrm.username  = "vagrant"
  config.winrm.password  = "vagrant"
  config.winrm.transport   = :plaintext
  config.winrm.timeout      = 1800
  config.winrm.retry_limit  = 120   # Windows first boot after Sysprep takes 8-15+ min;
  config.winrm.retry_delay  = 10    # 120 x 10s = 20 min of retries within boot_timeout
  config.vm.boot_timeout    = 1800  # 30 min overall boot window

  # ── SSH credentials (for 'vagrant ssh' / manual access) ──────────────────────
  config.ssh.username   = "vagrant"
  config.ssh.password   = "vagrant"
  config.ssh.insert_key = false
  config.ssh.extra_args = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]

  # ── Disable default /vagrant synced folder (not needed for this lab) ─────────
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # ==========================================================================
  # QEMU HARDWARE QUIRKS (Matching the Packer Build)
  # These must exactly match the settings used in windows-sql.pkr.hcl or
  # Windows will BSOD with INACCESSIBLE_BOOT_DEVICE on first boot.
  # ==========================================================================
  config.vm.provider "qemu" do |qe|
    # Explicitly set qemu_dir to avoid vagrant-qemu defaulting to macOS path on Linux
    qe.qemu_dir = "/usr/share/qemu"

    # Machine Architecture: MUST match Packer build (pc = i440fx, NOT q35)
    qe.machine         = "pc"
    qe.arch            = "x86_64"
    qe.cpu             = "host"     # correct attr is 'cpu', not 'cpu_model'

    # Drivers: Windows native drivers only — no VirtIO out of the box
    qe.net_device      = "e1000e"
    qe.drive_interface = "ide"

    # Auto-correct SSH port collision
    qe.ssh_auto_correct = true

    # NOTE: extra_qemu_args is set per-machine below (includes -enable-kvm,
    # -display none, AND the socket NIC for inter-VM networking)
  end

  # ============================================================================
  # Region: RegionA — Network: 192.168.10.0/24
  # Multicast port for inter-VM socket NIC: 5000
  # ============================================================================
  config.vm.define "dc01", primary: true do |machine|
    # NOTE: machine.vm.hostname is intentionally NOT set here.
    # Vagrant's built-in Windows hostname setter conflicts with Set-Hostname.ps1.
    machine.vm.box      = "win2022-sql2022"
    machine.vm.box_url  = "file:///opt/vagrant-boxes/win2022-sql2022.box"

    # ── Per-VM QEMU overrides ─────────────────────────────────────────────────
    # - qe.ssh_port: unique host port for QEMU user-mode hostfwd
    # - qe.smp: vCPU count (correct attr; 'cpus' is silently ignored)
    # - extra_qemu_args: MUST include -enable-kvm/-display here because
    #   per-machine args REPLACE global args in vagrant-qemu's merge.
    #   Socket NIC provides inter-VM networking (all VMs in a region share
    #   multicast group 230.0.0.1:5000 as a virtual switch).
    machine.vm.provider "qemu" do |qe|
      qe.smp      = "2"
      qe.memory   = "2048M"
      qe.ssh_port = 50022
      # vagrant-qemu automatically adds WinRM hostfwd rules (port 5985 + 5986)
      # from machine.winrm.port when communicator=winrm. No extra_netdev_args needed.
      qe.extra_qemu_args = [
        "-enable-kvm", "-display", "none",
        "-netdev", "socket,id=lab-net,mcast=230.0.0.1:5000",
        "-device", "e1000e,netdev=lab-net"
      ]
    end

    # Vagrant SSH port (for 'vagrant ssh' and provisioner communication)
    machine.ssh.port   = 50022

    # ── Static IP via private network (ignored by QEMU provider; Set-StaticIP.ps1
    #    configures the NIC inside the guest) ─────────────────────────────────
    machine.vm.network "private_network",
      ip:           "192.168.10.10",
      netmask:      "0.255.255.255",
      virtualbox__intnet: "regiona_net"

    # ── Provisioning order ───────────────────────────────────────────────────
    # 1. Set static IP — TEMPORARILY DISABLED for SSH failure isolation
    # machine.vm.provision "Set-StaticIP", type: "shell",
    #   path:              "provisioners/Set-StaticIP.ps1",
    #   privileged:        true,
    #   powershell_elevated_interactive: false,
    #   args:              [
    #     "192.168.10.10",
    #     "24",
    #     "192.168.10.1",
    #     "192.168.10.10"
    #   ]

    # 2. Rename computer — using inline to bypass file-upload/path issues on Windows SSH
    machine.vm.provision "Set-Hostname", type: "shell",
      inline: "Rename-Computer -NewName 'dc01' -Force"
    machine.vm.provision "reboot-after-rename", type: "reload"

    # 2b. Disable SQL Server service (box has SQL pre-staged; DC doesn't need it)
    machine.vm.provision "Disable-SqlServer", type: "shell",
      path:       "provisioners/Disable-SqlServer.ps1",
      privileged: true

    # 3a. Promote to Domain Controller — then reload via provider
    machine.vm.provision "Install-ADDS", type: "shell",
      path:    "provisioners/Install-ADDSForest.ps1",
      privileged: true,
      args:    [
        "test.dev",
        "P@ssw0rd",
        "Forest"  # "Forest" or "Replica"
      ]
    machine.vm.provision "reboot-after-adds", type: "reload"

    # 3b. Create lab admin account (only on the first/forest DC)
    machine.vm.provision "New-LabAdmin", type: "shell",
      path:    "provisioners/New-LabAdminAccount.ps1",
      privileged: true,
      args:    [
        "test.dev",
        "admin",
        "P@ssw0rd"
      ]

  end  # define dc01
  config.vm.define "sql01", primary: false do |machine|
    # NOTE: machine.vm.hostname is intentionally NOT set here.
    # Vagrant's built-in Windows hostname setter conflicts with Set-Hostname.ps1.
    machine.vm.box      = "win2022-sql2022"
    machine.vm.box_url  = "file:///opt/vagrant-boxes/win2022-sql2022.box"

    # ── Per-VM QEMU overrides ─────────────────────────────────────────────────
    # - qe.ssh_port: unique host port for QEMU user-mode hostfwd
    # - qe.smp: vCPU count (correct attr; 'cpus' is silently ignored)
    # - extra_qemu_args: MUST include -enable-kvm/-display here because
    #   per-machine args REPLACE global args in vagrant-qemu's merge.
    #   Socket NIC provides inter-VM networking (all VMs in a region share
    #   multicast group 230.0.0.1:5000 as a virtual switch).
    machine.vm.provider "qemu" do |qe|
      qe.smp      = "4"
      qe.memory   = "4096M"
      qe.ssh_port = 50023
      # vagrant-qemu automatically adds WinRM hostfwd rules (port 5985 + 5986)
      # from machine.winrm.port when communicator=winrm. No extra_netdev_args needed.
      qe.extra_qemu_args = [
        "-enable-kvm", "-display", "none",
        "-netdev", "socket,id=lab-net,mcast=230.0.0.1:5000",
        "-device", "e1000e,netdev=lab-net"
      ]
    end

    # Vagrant SSH port (for 'vagrant ssh' and provisioner communication)
    machine.ssh.port   = 50023

    # ── Static IP via private network (ignored by QEMU provider; Set-StaticIP.ps1
    #    configures the NIC inside the guest) ─────────────────────────────────
    machine.vm.network "private_network",
      ip:           "192.168.10.20",
      netmask:      "0.255.255.255",
      virtualbox__intnet: "regiona_net"

    # ── Provisioning order ───────────────────────────────────────────────────
    # 1. Set static IP — TEMPORARILY DISABLED for SSH failure isolation
    # machine.vm.provision "Set-StaticIP", type: "shell",
    #   path:              "provisioners/Set-StaticIP.ps1",
    #   privileged:        true,
    #   powershell_elevated_interactive: false,
    #   args:              [
    #     "192.168.10.20",
    #     "24",
    #     "192.168.10.1",
    #     "192.168.10.10"
    #   ]

    # 2. Rename computer — using inline to bypass file-upload/path issues on Windows SSH
    machine.vm.provision "Set-Hostname", type: "shell",
      inline: "Rename-Computer -NewName 'sql01' -Force"
    machine.vm.provision "reboot-after-rename", type: "reload"

    # 3a. Wait for DC and join domain — then reload via provider
    machine.vm.provision "Join-Domain", type: "shell",
      path:    "provisioners/Join-Domain.ps1",
      privileged: true,
      args:    [
        "test.dev",
        "192.168.10.10",
        "admin",
        "P@ssw0rd"
      ]
    machine.vm.provision "reboot-after-join", type: "reload"

    # 3b. SQL Server CompleteImage
    machine.vm.provision "Complete-SqlImage", type: "shell",
      path:    "provisioners/Complete-SqlImage.ps1",
      privileged: true,
      args:    [
        "test.dev",
        "admin",
        "P@ssw0rd"
      ]

    # 3c. dbatools post-configuration
    machine.vm.provision "Configure-SqlServer", type: "shell",
      path:    "provisioners/Configure-SqlServer.ps1",
      privileged: true,
      args:    [
        "P@ssw0rd"
      ]

  end  # define sql01

end
