# Vagrantfile template embedded in the Vagrant .box produced by Packer.
# This is NOT the Vagrantfile used at lab deployment time — that is generated by Deploy-Lab.ps1
# from Vagrantfile.erb. This template sets box-level defaults that apply before the
# project-level Vagrantfile overrides them.
#
# Key: tell Vagrant this box uses SSH (not WinRM) as its communicator.
Vagrant.configure("2") do |config|
  config.vm.communicator = "ssh"
  config.ssh.username    = "vagrant"
  config.ssh.password    = "vagrant"
end
